### ISSUE TITLE
Building on OpenBSD

### ISSUE THREAD

**Issue by lightningx10** [jtsiomb/xlivebg#7] opened 2021-09-29 11:43 UTC
I am building on OpenBSD and I've run into a few issues, firstly many `#ifndef` operations needed to be changed to include OpenBSD, that's fine and everything seems to almost compile now, but then I get to the included libraries `libimago` and `treestore`.

In `libimago/src/file_lbm.c` there seems to be some very strange declarations that neither gcc or clang seem to recognise as valid, around line 115 the following is defined:
```
static uint16_t swap16(uint16_t x);
static uint32_t swap32(uint32_t x);
```
gcc says that it's expecting declaration specifiers, and clang just seems to complain about missing brackets. Is there any simple fix for this?

**Comment by lightningx10** [comment] 2021-09-29 11:49
I managed to fix this by renaming the functions, apparantly the name `swap16(uint16_t)` is already taken, something should be done to fix this in source.

**Comment by lightningx10** [comment] 2021-09-29 12:07
It also seems that `-ldl` cannot be found, I was unable to locate where this might be so that I could add it to the libraries so I just excluded it

**Comment by lightningx10** [comment] 2021-09-29 12:28
After finally building it, the standalone `xlivebg` executable does not change the background at all, and the `xlivebg-gui` gets a segmentation fault if `xlivebg` is actually running, else it asks if `xlivebg` is running.

**Comment by jtsiomb** [comment] 2021-09-29 13:58
I don't have an OpenBSD system. Can you be more specific about the necessary `#ifdef` changes required to build on OpenBSD, so that I can make the changes? Alternatively please send a pull request containing only this part of your changes.

The swap16/swap32 problen is clearly caused by some OpenBSD header using the same name as a macro. Renaming them is the simplest solution. I'll do that.

`libdl` is part of libc, and contains the dynamic loader functions (dlopen/dlsym) on most UNIX systems. I'll have to make it conditional for OpenBSD.

For the runtime issues please open two separate bug reports and make sure to specify which window manager you're using for the firs one, and a backtrace for the xlivebg-gui crash. Also try passing `-n` to xlivebg.

**Comment by jtsiomb** [comment] 2021-09-30 03:01
Fixed the build issues, and also the GUI crashing bug. Closing this bug report. If you still have issues with the build, please continue posting here. If you still have issues with crashes or xlivebg not working as expected in some other way, please open new bug reports specific to the problem you're facing.

**Closed by jtsiomb** 2021-09-30 03:01 UTC

**Comment by lightningx10** [comment] 2021-09-30 03:45
Thank you I was just about to get back to you about what to change and saw that you'd already fixed it, it compiles now! I'll open a separate issue for the background not setting the root correctly.
