### ISSUE TITLE
Deprecated ffmpeg methods used, causes errors when attempting to compile

### ISSUE THREAD

**Issue by FlareStormGaming** [jtsiomb/xlivebg#13] opened 2022-06-04 20:31 UTC
![image](https://user-images.githubusercontent.com/70780971/172024588-a788e0ad-f5c9-478e-8897-a7986d638fe9.png)

As shown here, AVStream has no member named 'codec' for ffmpeg... 
It was deprecated recently, in favor of `codecpar`. 

I would downgrade my ffmpeg, but Arch is rolling-release.

**Comment by FlareStormGaming** [comment] 2022-06-04 20:41
Secondary note: from pacman, I have ffmpeg 2:5.0-7 and ffmpeg4.4 4.4.1-5 installed. It's the video plugin causing the issue, I think, but I also have the weird bug of not being able to draw over the root window (using KDE Plasma, `kwin_x11` as my DE). I circumented it by calling `xlivebg -n`, but then the window had weird borders. I thought it might be because I have a tiling script for windows, but even when I disabled it the issue persisted. 

Another issue is that whenever I click the wallpaper, the wallpaper just seems to vanish. It disappears until I refocus on the terminal that I spawned the xlivebg process from, and it never seems to quite recover (stays black) even after. If I click on it, or focus on any other window, it disappears; it shows as a black window when i'm focused on terminal. It works when I enable it initially but if I click off and back it's black.

**Comment by jtsiomb** [comment] 2022-06-05 02:31
Unfortunately ffmpeg breaks backwards compatibility all the time. The video plugin was a bad idea all around. It's the main source of trouble and it sucks way too many resources. I should really get rid of it.

Having said that, this is a duplicate bug report. See issue #10. So I'll close it. Please create separate issues for any other problem you encountered. Having to use `-n` with KDE is not a bug, but the strange borders issue and the vanishing wallpaper bug should have their own bug reports, with as much information as possible to try and reproduce them.

**Closed by jtsiomb** 2022-06-05 02:31 UTC
