### ISSUE TITLE
Picom background not displaying

### ISSUE THREAD

**Issue by lightningx10** [jtsiomb/xlivebg#8] opened 2021-09-30 04:05 UTC
I am running OpenBSD with dwm and a compositor picom, and xlivebg is unable to change the background image, only working with `-n` or with the compositor turned off.

Is there any way of getting this to work with an external compositor? The `-n` flag does not actually set it as a background but just as a window that I cannot move or resize.

**Comment by jtsiomb** [comment] 2021-09-30 05:26
I have encountered similar problems in the past when trying to run xlivebg with the xcompmgr compositor. Some other compositors I tried, notably the xfce compositor seem to work fine.

The `-n` option makes xlivebg create a new full screen window, marked as a "desktop window", instead of trying to draw on the root or virtual root. If the window manager treats it correctly, it should not be distinguishable from the regular desktop/root/virtual root window. If that's not the case, it means that dwm lacks support (or has incomplete support) for the EWMH protocols, and specifically setting of `_NET_WM_WINDOW_TYPE` to `_NET_WM_WINDOW_TYPE_DESKTOP`.

**Comment by jtsiomb** [comment] 2021-09-30 05:40
I just checked the dwm source code, and indeed there's no reference to `_NET_WM_WINDOW_TYPE_DESKTOP`. The only type it seems to take into account is `_NET_WM_WINDOW_TYPE_DIALOG`. You should probably send a bug report/feature request to dwm about it.

Until dwm fixes this issue, your only option is to either find a different compositor that might work correctly, run without a compositor, or use a different window manager. I don't think there's anything I can do about it.

Since this is not a bug in xlivebg, and I don't intend to debug the compositors either (I never use a compositor myself, so I don't have much interest in fixing them), I'm closing the bug report.

**Closed by jtsiomb** 2021-09-30 05:40 UTC

**Comment by lightningx10** [comment] 2021-09-30 06:47
Thank you for the leads, I'll make a patch for dwm to fix this behaviour
